export const seatList = [
  "E-119",
  "E-120",
  "E-117",
  "E-118",
  "E-121",
  "E-122",
  "E-116",
  "E-123",
];

// Here is a list of players for Vissel Kobe, the champions of the J.League for the 2023 season:
export const players = [
  { number: 1, name: "Maekawa Keiya" },
  { number: 2, name: "Iino Nanasei" },
  { number: 3, name: "Mateus Turel" },
  { number: 4, name: "Yamakawa Tetsushi" },
  { number: 6, name: "Ogiwara Takahiro" },
  { number: 7, name: "Ideguchi Ryosuke" },
  { number: 9, name: "Miyashiro Daisei" },
  { number: 10, name: "Osako Yuuya" },
  { number: 11, name: "Muto Yoshinori" },
  { number: 14, name: "Taki Yasuya" },
  { number: 15, name: "Honda Yuki" },
  { number: 16, name: "Saito Mitsuki" },
  { number: 18, name: "Ide Haruya" },
  { number: 19, name: "Hatsuse Ryo" },
  { number: 21, name: "Arai Shota" },
  { number: 22, name: "Sasaki Taiki" },
  { number: 23, name: "Hirose Rikuto" },
  { number: 24, name: "Sakai Takanori" },
  { number: 25, name: "Kuwashiro Yuya" },
  { number: 26, name: "Jean Patric" },
  { number: 29, name: "Linkon" },
  { number: 30, name: "Yamauchi Sho" },
  { number: 31, name: "Nakasaka Yuya" },
  { number: 33, name: "Honma Justin" },
  { number: 37, name: "Terasaka Shogo" },
  { number: 39, name: "Takayama Shio" },
  { number: 44, name: "Hidaka Kouki" },
  { number: 50, name: "Obi Powell Obinna" },
  { number: 55, name: "Iwanami Takuya" },
  { number: 81, name: "Kikuchi Ryuho" },
  { number: 96, name: "Yamaguchi Hotaru" }
];
