export const seatList = [
  "E-119",
  "E-120",
  "E-117",
  "E-118",
  "E-121",
  "E-122",
  "E-116",
  "E-123",
];

export const players = [
  { number: 1, name: "前川黛也" },
  { number: 2, name: "飯野七聖" },
  { number: 3, name: "マテウス・トゥーレル" },
  { number: 4, name: "山川哲史" },
  { number: 6, name: "扇原貴宏" },
  { number: 7, name: "井手口陽介" },
  { number: 9, name: "宮代大聖" },
  { number: 10, name: "大迫勇也" },
  { number: 11, name: "武藤嘉紀" },
  { number: 14, name: "汰木康也" },
  { number: 15, name: "本多勇喜" },
  { number: 16, name: "齊藤未月" },
  { number: 18, name: "井出遥也" },
  { number: 19, name: "初瀬亮" },
  { number: 21, name: "新井章太" },
  { number: 22, name: "佐々木大樹" },
  { number: 23, name: "広瀬陸斗" },
  { number: 24, name: "酒井高徳" },
  { number: 25, name: "鍬先祐弥" },
  { number: 26, name: "ジェアン・パトリッキ" },
  { number: 29, name: "リンコン" },
  { number: 30, name: "山内翔" },
  { number: 31, name: "中坂勇哉" },
  { number: 33, name: "本間ジャスティン" },
  { number: 37, name: "寺阪尚悟" },
  { number: 39, name: "高山汐生" },
  { number: 44, name: "日高光揮" },
  { number: 50, name: "オビ・パウエル・オビンナ" },
  { number: 55, name: "岩波拓也" },
  { number: 81, name: "菊池流帆" },
  { number: 96, name: "山口蛍" }
];
